"""
Is responsible for writing given data into csv files.
"""

import os


def create_csv(csv_filepaths, header_row, value_rows, timestamps):
    """
    Creates CSV tables from data collected before.
    :param csv_filepaths: the paths, the csv tables generated by this function should be saved.
    :param header_row: table's first row which contains the instance names this table has values
    for.
    :param value_rows: rows of table which contain value material.
    :param timestamps: a list of timestamps, each belonging to a value row in the table.
    """

    for table in range(len(csv_filepaths)):

        with open(csv_filepaths[table], 'w') as table_file:

            # write first row which contains the headers into csv
            headline = 'time'  # first column in table should label the x-axis
            for instance in header_row[table]:
                # print(instance)
                headline += ', '
                headline += instance

            # write out line
            table_file.write(headline + os.linesep)

            # write data rows into csv
            # (you have to iterate over a three times interlaced list for this)
            for iteration in range(len(value_rows[table])):

                row = value_rows[table][iteration]

                # in the table's first column always stands the time stamp
                data_line = str(timestamps[iteration])

                # write a value from each instance into one line
                for entry in row:
                    data_line += ', '
                    data_line += entry

                # write out line
                table_file.write(data_line + os.linesep)

        table_file.close()
        print('Wrote graph values into ' + csv_filepaths[table])
